# Generated by Django 6.1.1 on 2026-10-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_metadata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsource',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadsource',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
