# Generated by Django 6.1.1 on 2026-10-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('lead', 'Lead'), ('contacted', 'Contacted'), ('prospect', 'Prospect'), ('customer', 'Customer'), ('lost', 'Lost')], default='lead', max_length=20),
        ),
    ]
